import { Stack, StackProps, Duration, RemovalPolicy, CfnOutput } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Bucket, BlockPublicAccess, BucketEncryption } from 'aws-cdk-lib/aws-s3';
import { Table, AttributeType, BillingMode } from 'aws-cdk-lib/aws-dynamodb';
import { Runtime, FunctionUrlAuthType, HttpMethod, InvokeMode } from 'aws-cdk-lib/aws-lambda';
import { PolicyStatement, Effect } from 'aws-cdk-lib/aws-iam';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import { RetentionDays } from 'aws-cdk-lib/aws-logs';
import { CfnBudget } from 'aws-cdk-lib/aws-budgets';
import { Secret } from 'aws-cdk-lib/aws-secretsmanager';
import * as path from 'path';

// Telemetry ingest for the Performance app.
//
// Shape:
//   App → POST (gzipped log, headers X-Install-Id / X-Commit / X-Version,
//               Authorization: Bearer <token>) → Lambda function URL
//   Lambda validates bearer token, writes to S3, upserts install record in
//   DynamoDB. Bucket keeps objects for 1 year; stack retention for bucket
//   is RETAIN so teardown doesn't destroy accumulated logs.
//
// Notes:
//   - The bearer token is regenerated on first deploy and stored in SSM
//     Parameter Store under /performance/telemetry/bearer-token. Subsequent
//     deploys reuse the stored value so the token is stable across changes.
//   - CORS origin is wide open since the client is a macOS app (no browser).
//   - Monthly budget alarm at $5 with email notification at 80%.
export class TelemetryStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const notificationEmail = this.node.tryGetContext('notificationEmail') as string;

    // Session-log storage. Lifecycle: expire objects after 1 year; keep bucket on stack destroy.
    const bucket = new Bucket(this, 'SessionLogs', {
      bucketName: `performance-session-logs-${this.account}`,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      lifecycleRules: [{ expiration: Duration.days(365) }],
      removalPolicy: RemovalPolicy.RETAIN,
    });

    // Per-installation metadata. Write-only from the Lambda; queryable via AWS console.
    const installations = new Table(this, 'Installations', {
      tableName: 'performance-installations',
      partitionKey: { name: 'installationId', type: AttributeType.STRING },
      billingMode: BillingMode.PAY_PER_REQUEST,
      removalPolicy: RemovalPolicy.RETAIN,
    });

    // Bearer token — auto-generated by Secrets Manager on first deploy, stable
    // across redeploys (the value is created once by the service and never
    // appears in the CDK template). Not a secret in the security sense — the
    // app ships the token baked in; role is rate-limiting + "are you a
    // Performance app or random spam." Rotate by deleting the secret in the
    // AWS console and redeploying.
    const tokenSecret = new Secret(this, 'BearerTokenSecret', {
      secretName: 'performance/telemetry/bearer-token',
      description: 'Shared bearer token embedded in Performance app builds',
      generateSecretString: {
        excludePunctuation: true,
        passwordLength: 43,  // ~32 bytes of entropy
      },
    });

    const ingest = new NodejsFunction(this, 'Ingest', {
      entry: path.join(__dirname, '..', 'lambda', 'ingest.ts'),
      handler: 'handler',
      runtime: Runtime.NODEJS_20_X,
      timeout: Duration.seconds(30),
      memorySize: 256,
      logRetention: RetentionDays.ONE_MONTH,
      environment: {
        BUCKET: bucket.bucketName,
        TABLE: installations.tableName,
        BEARER_TOKEN_SECRET: tokenSecret.secretArn,
      },
    });

    bucket.grantPut(ingest);
    installations.grantWriteData(ingest);
    tokenSecret.grantRead(ingest);

    const url = ingest.addFunctionUrl({
      authType: FunctionUrlAuthType.NONE,
      cors: {
        allowedOrigins: ['*'],
        allowedMethods: [HttpMethod.POST],
        allowedHeaders: ['authorization', 'content-type', 'content-encoding',
                         'x-install-id', 'x-commit', 'x-version'],
      },
    });

    // ---- Chat proxy (AI for testers) ---------------------------------------
    //
    // See docs/LAMBDA_CHAT_PROXY.md for the full design.
    //
    // The Anthropic API key is stored as a SecureString SSM parameter that
    // must be created out-of-band before first deploy:
    //
    //   aws ssm put-parameter --name /performance/chat/anthropic-api-key \
    //       --type SecureString --value sk-ant-... --no-overwrite
    //
    // We reference it by name rather than letting CDK manage it so the secret
    // value never appears in CloudFormation templates or stack diffs.
    const anthropicKeyParamName = '/performance/chat/anthropic-api-key';

    const chat = new NodejsFunction(this, 'ChatProxy', {
      entry: path.join(__dirname, '..', 'lambda', 'chat.ts'),
      handler: 'handler',
      runtime: Runtime.NODEJS_20_X,
      timeout: Duration.minutes(5),  // long-running for streaming responses
      memorySize: 512,
      logRetention: RetentionDays.ONE_MONTH,
      environment: {
        TABLE: installations.tableName,
        BEARER_TOKEN_SECRET: tokenSecret.secretArn,
        ANTHROPIC_KEY_PARAM: anthropicKeyParamName,
        DEFAULT_MODEL: 'claude-sonnet-4-5',
        MONTHLY_INPUT_CAP: '100000',
        MONTHLY_OUTPUT_CAP: '25000',
        UNCAPPED_INSTALLS: '',  // CSV of install IDs to bypass the cap (dev use)
      },
    });

    installations.grantReadWriteData(chat);
    tokenSecret.grantRead(chat);
    chat.addToRolePolicy(new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['ssm:GetParameter'],
      resources: [`arn:aws:ssm:${this.region}:${this.account}:parameter${anthropicKeyParamName}`],
    }));

    const chatUrl = chat.addFunctionUrl({
      authType: FunctionUrlAuthType.NONE,
      invokeMode: InvokeMode.RESPONSE_STREAM,
      cors: {
        allowedOrigins: ['*'],
        allowedMethods: [HttpMethod.POST],
        allowedHeaders: ['authorization', 'content-type', 'x-install-id'],
      },
    });

    // ------------------------------------------------------------------------

    // Cost alarm — email at 80% of $50/month. Headroom for chat traffic at
    // small population scale (see docs/LAMBDA_CHAT_PROXY.md cost model).
    if (notificationEmail) {
      new CfnBudget(this, 'MonthlyBudget', {
        budget: {
          budgetType: 'COST',
          timeUnit: 'MONTHLY',
          budgetLimit: { amount: 50, unit: 'USD' },
          budgetName: 'performance-telemetry',
          costFilters: {
            TagKeyValue: ['user:Project$Performance'],
          },
        },
        notificationsWithSubscribers: [{
          notification: {
            notificationType: 'ACTUAL',
            comparisonOperator: 'GREATER_THAN',
            threshold: 80,
            thresholdType: 'PERCENTAGE',
          },
          subscribers: [{
            subscriptionType: 'EMAIL',
            address: notificationEmail,
          }],
        }],
      });
    }

    new CfnOutput(this, 'IngestUrl', {
      value: url.url,
      description: 'Endpoint the app POSTs session logs to',
    });
    new CfnOutput(this, 'ChatProxyUrl', {
      value: chatUrl.url,
      description: 'Endpoint the app POSTs chat requests to (Anthropic proxy)',
    });
    new CfnOutput(this, 'BearerTokenSecretName', {
      value: tokenSecret.secretName,
      description: 'Read via: aws secretsmanager get-secret-value --secret-id ...',
    });
    new CfnOutput(this, 'BucketName', {
      value: bucket.bucketName,
      description: 'S3 bucket holding session logs',
    });
    new CfnOutput(this, 'TableName', {
      value: installations.tableName,
      description: 'DynamoDB table with per-installation metadata',
    });
  }
}
