# Generates BuildVersion.h from current git state. Invoked at build time
# via `cmake -D... -P`, so the baked commit hash can never lag the binary.
# Writes idempotently — if the produced content matches what's already on
# disk, the file's mtime is untouched and dependents don't recompile.
#
# Required inputs (pass via -D on the cmake command line):
#   OUTPUT          — absolute path to the .h file to write
#   SOURCE_DIR      — project source dir (for git invocation)
#   PROJECT_VERSION — CMake project version string (e.g. "0.0.1")

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

execute_process(
    COMMAND git describe --tags --exact-match HEAD
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE GIT_TAG
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

# diff-index vs HEAD returns 0 if clean, nonzero if there are unstaged or
# staged changes to tracked files. (Untracked files are not considered
# "dirty" here — standard convention matching `git describe --dirty`.)
execute_process(
    COMMAND git diff-index --quiet HEAD --
    WORKING_DIRECTORY ${SOURCE_DIR}
    RESULT_VARIABLE GIT_DIRTY_RESULT
    ERROR_QUIET
)

if(NOT GIT_COMMIT)
    set(GIT_COMMIT "unknown")
endif()
if(NOT GIT_TAG)
    set(GIT_TAG "")
endif()
if(GIT_DIRTY_RESULT EQUAL 0)
    set(GIT_DIRTY_LITERAL "false")
    set(GIT_DIRTY_SUFFIX "")
else()
    set(GIT_DIRTY_LITERAL "true")
    set(GIT_DIRTY_SUFFIX "-dirty")
endif()

set(CONTENT "// Auto-generated by cmake/GenerateBuildVersion.cmake — do not edit.
#pragma once

#define BUILD_GIT_COMMIT \"${GIT_COMMIT}${GIT_DIRTY_SUFFIX}\"
#define BUILD_GIT_TAG    \"${GIT_TAG}\"
#define BUILD_GIT_DIRTY  ${GIT_DIRTY_LITERAL}
#define BUILD_VERSION    \"${PROJECT_VERSION}\"
")

# Idempotent write — only touch the file if content differs, so consumers
# that include this header don't needlessly recompile.
if(EXISTS ${OUTPUT})
    file(READ ${OUTPUT} EXISTING)
    if(EXISTING STREQUAL CONTENT)
        return()
    endif()
endif()
file(WRITE ${OUTPUT} "${CONTENT}")
