# Generates BuildConfig.h from keys/telemetry.json. Runs at build time.
# If the config file is absent (fresh checkout without running
# scripts/fetch-telemetry-config.sh), emits empty strings so the shipper
# becomes a no-op and builds still work. Write is idempotent.
#
# Required inputs (pass via -D on the cmake command line):
#   OUTPUT     — absolute path to the .h file to write
#   SOURCE_DIR — project source dir (for reading keys/telemetry.json)

set(CONFIG_FILE "${SOURCE_DIR}/keys/telemetry.json")
set(TELEMETRY_URL "")
set(TELEMETRY_TOKEN "")

if(EXISTS "${CONFIG_FILE}")
    file(READ "${CONFIG_FILE}" CONFIG_CONTENT)
    string(REGEX MATCH "\"url\"[ \t]*:[ \t]*\"([^\"]*)\"" _ "${CONFIG_CONTENT}")
    set(TELEMETRY_URL "${CMAKE_MATCH_1}")
    string(REGEX MATCH "\"token\"[ \t]*:[ \t]*\"([^\"]*)\"" _ "${CONFIG_CONTENT}")
    set(TELEMETRY_TOKEN "${CMAKE_MATCH_1}")
endif()

set(CONTENT "// Auto-generated by cmake/GenerateBuildConfig.cmake — do not edit.
// Contents come from keys/telemetry.json at build time. Absent file =
// empty values = telemetry shipper is a no-op.
#pragma once

#define TELEMETRY_URL   \"${TELEMETRY_URL}\"
#define TELEMETRY_TOKEN \"${TELEMETRY_TOKEN}\"
")

if(EXISTS ${OUTPUT})
    file(READ ${OUTPUT} EXISTING)
    if(EXISTING STREQUAL CONTENT)
        return()
    endif()
endif()
file(WRITE ${OUTPUT} "${CONTENT}")
